name: Build & Test

on:
  push:
    branches:
      - 'master'
      - 'v3.0.0-dev'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    strategy:
      matrix:
        node: [12.10.0]
        os: ['ubuntu-latest', 'windows-latest']

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Prettier dry-run
        run: npm run prettier.dry-run
        shell: bash

      - name: Build
        run: npm run build -- --ci


      - name: Start BrowserStack
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12.10.0'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}

      - name: Run karma tests
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12.10.0'
        run: npm run test.karma.prod
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}

      - name: Stop BrowserStack
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12.10.0'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
